### ISSUE TITLE
Add reCAPTCHA to the contact form just a small suggestion Kaustubh

### ISSUE THREAD

**Issue by namnaku87** [kaustubhai/portfolio-template#10]
Your Portfolio Template looks great and awesome clean and responsive but if you add captcha would do better bro because it protect the integrity of online polls by stopping hackers using robots to send in repeated false responses. Will you do that. Thanks.

**Comment by kaustubhai** [comment]
If you are going to use formspree like I suggested in your contact form,
you can add reCaptcha to your form over there.
Tell me if you need any help with that

**Comment by namnaku87** [comment]
First of all thanks for your immediate reply. Really appreciate it.  Yeah i saw formspree in the template i will be using it for the contact form as you suggested. How may i do that? can you help in adding i actually forked your project can you help me to add that reCaptcha to the contact form, below the send button form would do better.

**Comment by namnaku87** [comment]
Are you doing it Kaustubh?

**Comment by kaustubhai** [comment]
Sorry for the delay
The thing with third parties services is that most of them don't provide a lot of customisations. I don't think you can apply reCaptcha just below the form but what you can do is create a form on form spree and then in the form setting, you can just enable the reCaptcha shown in the image. To experience this in action, you can go to my personal website [here](https://kaustubhai.me)
![image](https://i.imgur.com/MR5Dh6s.png)

**Comment by namnaku87** [comment]
That really works well thanks Kaustubh. By the way your your own portfolio looks beautiful and aesthetic.
