### ISSUE TITLE
Where are the favicons/icons added in the code?

### ISSUE THREAD

**Issue by m000lie** [kaustubhai/portfolio-template#13]
hello, I can't find where the favicons and logos are added. pls tell me which file they are added in

**Comment by aknahin** [comment]
In [this](https://github.com/kaustubhai/portfolio-template/blob/f26e6c85681e487bf7d827e980c8ed055495b4b5/public/index.html#L5) line favicon are added and in [this](https://github.com/kaustubhai/portfolio-template/blob/f26e6c85681e487bf7d827e980c8ed055495b4b5/public/index.html#L16) line logo are added. 
![image](https://user-images.githubusercontent.com/58381178/235667068-20d862cd-007e-4241-a33b-9f5cf7a7e7b3.png)
