### ISSUE TITLE
Regarding your template

### ISSUE THREAD

**Issue by Tharun-tharun** [kaustubhai/portfolio-template#2]
Hi,

I saw your template it was static and well designed but i just wanted to know how do i add additional content like (eg): 
 
 I just want to add Experience (like a timeline) in your template how do i do that, for example, i attached a sample screenshot of it take a look at it, or anything similar to it any suggestion from you is also fine.
![Untitled25](https://user-images.githubusercontent.com/41158838/124711836-65997480-deb3-11eb-86d0-af160336ce64.png)
 
Education
 
Projects
 
Certifications

**Comment by varun-singhh** [comment]
This is a template and the template means you can just edit the fields in here if you want something new you have to create it yourself. Although I can suggest you npm package for same called **react-event-timeline**, you can build timeline easily using following pacakge.

**Comment by Tharun-tharun** [comment]
> This is a template and the template means you can just edit the fields in here if you want something new you have to create it yourself. Although I can suggest you npm package for same called **react-event-timeline**, you can build timeline easily using following pacakge.

This is ample for me, Thank you so much for your help means a lot to me.
