### ISSUE TITLE
how Style fitting in your template

### ISSUE THREAD

**Issue by Tharun-tharun** [kaustubhai/portfolio-template#5]
Hi there,

I just wanted to know how to get a different slide flip-style just like yours (https://kaustubhai.netlify.app/) that is like when you go to "get in touch" style is something different it goes like flip-style, how do i bring the same style.

also how do i bring laptop style with background color like this

**Comment by kaustubhai** [comment]
Still not able to get you brother

**Comment by Tharun-tharun** [comment]
Bro are you in telegram so that it will be easier for me to get you in private I need some private conversation. Will that be possible if you do, please mail me on tharunaiyadhav@gmail.com

**Comment by Tharun-tharun** [comment]
I would like to load the TensorFlow icon in the template how do i do import Iconify SVG framework (https://iconify.design/icon-sets/logos/tensorflow.html) it's only showing font awesome that you already loaded into it. Can you guide me on how to how to load iconify and Tensorflow icon.

![image](https://user-images.githubusercontent.com/41158838/125150066-b5fe1580-e0f1-11eb-8d34-27ae96362b94.png)
When i was trying to load TensorFlow it's not showing TensorFlow Icon on the template
