### ISSUE TITLE
[ Responsive Issue ] The Checkout Portfolio Button does not center itself in mobile version

### ISSUE THREAD

**Issue by AnirudhPanda** [kaustubhai/portfolio-template#6]

**Comment by kaustubhai** [comment]
Hey @AnirudhPanda, would you like to contribute for solving this issue?

**Comment by AnirudhPanda** [comment]
> Hey @AnirudhPanda, would you like to contribute for solving this issue?

Sure!

**Comment by AnirudhPanda** [comment]
Also a little spacing between the h1 and p would have a good look on UI

**Comment by kaustubhai** [comment]
> 
> 
> > Hey @AnirudhPanda, would you like to contribute for solving this issue?
> 
> Sure!

Go ahead

**Comment by kaustubhai** [comment]
> 
> 
> Also a little spacing between the h1 and p would have a good look on UI

Please do it on a separate PR and not in the one with the bug resolve

**Comment by AnirudhPanda** [comment]
#7 FIXED
